kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.generalInfo.name }}-configmap
  namespace: {{ .Values.generalInfo.namespace | default "default" }}
data:
  log_level: INFO
  build_mode: Debug