kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.generalInfo.name }}-configmap
  namespace: {{ .Values.generalInfo.namespace | default "default" }}
  labels:
    {{- range $key, $val := .Values.generalInfo.labels -}}
      {{ $key | nindent 4 }}: {{ $val | quote }}
    {{- end }}
data: 
  appsettings.json: {{ .Files.Get .Values.configmap.pathtofile | printf "%s" | nindent 4 }}

    # appsettings.json: |-
    #   {
    #     "ConnectionStrings": {
    #       "VbsDb": "Server=some-connection-string"
    #     },
    #     "Logging": {
    #       "LogLevel": {
    #         "Default": "Information",
    #         "Microsoft": "Warning",
    #         "Microsoft.Hosting.Lifetime": "Information"
    #       }
    #     },
    #     "AllowedHosts": "*"
    #   }


#   log_level: INFO
#   build_mode: Debug