kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.generalInfo.name }}-configmap
  namespace: {{ .Values.generalInfo.namespace | default "default" }}
  labels:
    {{- range $key, $val := .Values.generalInfo.labels -}}
      {{ $key | nindent 4 }}: {{ $val | quote }}
    {{- end }}
data: 
{{- if .Values.app_settings }}
  {{ (.Values.configmap_internal_name_offile | default "appsettings.json") }}: {{ toJson .Values.app_settings | nindent 4 }}
{{- else }}
  fail "Please check the app_setting value that was put in."
{{- end }}