apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.generalInfo.name | default .Release.Name }}-deployment
  namespace: {{ .Values.generalInfo.namespace | default "default" }}
  labels:
    {{- range $key, $val := .Values.generalInfo.labels -}}
      {{- $key | nindent 4 }}: {{ $val | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  revisionHistoryLimit: {{ .Values.deployment.historyLimit | default 10 }}
  selector:
    matchLabels:  
      name: {{ .Values.generalInfo.name | default .Release.Name }}-pod
  strategy:
  #  type: RollingUpdate (By default)
    # type: Recreate
  template:
    metadata:
      name: {{ .Values.generalInfo.name | default .Release.Name }}-pod
      namespace: {{ .Values.generalInfo.namespace | default "default" }}
      labels:
        name: {{ .Values.generalInfo.name | default .Release.Name }}-pod
    spec:
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 10 }}
      containers:
      - name: {{ .Values.generalInfo.name | default .Release.Name }}-pod
        image: {{ ( include "deploy.image-name" .) | quote }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy | default "IfNotPresent" }}
        volumeMounts: 
          {{- toYaml .Values.deployment.volumeMounts | nindent 10}}
        ports:
          - name: web
            containerPort: {{ .Values.deployment.containerPort | default "80" }}
            protocol: TCP
# define all of the ConfigMap's data as container environment variables
        # envFrom:
        #   - configMapRef:
        #       name: {{ .Values.generalInfo.name }}-configmap
        # env:
        #   - name: GF_SECURITY_ADMIN_USER
        #     valueFrom:
        #       secretKeyRef:
        #         name: grafana
        #         key: admin-user
        #   - name: GF_SECURITY_ADMIN_PASSWORD
        #     valueFrom:s
        #       secretKeyRef:
        #         name: grafana
        #         key: admin-password
        # - name: GREETING
        #   valueFrom:
        #     configMapKeyRef:
        #       name: demo-config
        #       key: greeting
        livenessProbe:
          {{- toYaml .Values.deployment.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.deployment.readinessProbe | nindent 10 }}
        resources:
          requests:
            {{- toYaml .Values.deployment.resources.requests | nindent 12 }}
          limits:
            {{- toYaml .Values.deployment.resources.limits | nindent 12 }}
      tolerations:
        {{- toYaml .Values.deployment.tolerations | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      volumes:
        - name: test-volume
          configMap:
            name: {{ .Values.generalInfo.name }}-configmap
    # - name: config
    #   configMap:
    #     name: grafana
    # - name: storage
    #   emptyDir: {}
