{{- if eq ( .Values.ingressenabled | default "false" ) "true" }}
{{ $ports := .Values.service.ports }}
{{ $host := .Values.ingress.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $.Values.generalInfo.name | default $.Release.Name }}-ingress
  namespace: {{ .Values.generalInfo.namespace | default "default" }}
  labels:
    {{- range $key, $val := .Values.generalInfo.labels -}}
      {{ $key | nindent 4 }}: {{ $val | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations -}}
      {{ $key | nindent 4 }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- if $host -}}
    {{- range $host }}
    - host: {{ $host.host }}
      http:
        paths:
        {{- if $host.paths }}
          {{- range $host.paths }}
          - path: {{ .path }}
            backend:
              service:
                name: {{ $.Values.generalInfo.name | default $.Release.Name }}-svc
                port:
                  name: {{ .backend.service.port.name }}
                  number: {{ .backend.service.port.number }}
          {{- end }}
        {{- else if $ports -}}
          {{- range $ports }}
          - path: "/"
            backend:
              serviceName: {{ $.Values.generalInfo.name | default $.Release.Name }}-svc
              servicePort: {{ .port }}
          {{- end }}
        {{- else }}
          - path: "/"
            backend:
              serviceName: {{ $.Values.generalInfo.name | default $.Release.Name }}-svc
              servicePort: {{ $.Values.service.externalPort | default "80" }}
        {{- end }}
    {{- end }}
  {{- else if $.Values.ingress.domain }}
    - host: {{ $.Values.ingress.domain }}
      http:
        paths:
        {{- if $ports }}
          {{- range $ports }}
          - path: "/"
            backend:
              serviceName: {{ $.Values.generalInfo.name | default $.Release.Name }}-svc
              servicePort: {{ .port }}
          {{- end }}
        {{- else }}
          - path: "/"
            backend:
              serviceName: {{ $.Values.generalInfo.name | default $.Release.Name }}-svc
              servicePort: {{ $.Values.service.externalPort | default "80" }}
        {{- end }}
  {{- else }}
    fail "Ingress is enabled but you didn't put in a value for the host field. Please set the .ingress.domain or .ingress.hosts[]."
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{ toYaml .Values.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}