{{ $ports := .Values.service.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.generalInfo.name | default .Release.Name }}-svc
  namespace: {{ .Values.generalInfo.namespace | default "default" }}
  labels:
    {{- range $key, $val := .Values.generalInfo.labels -}}
      {{ $key | nindent 4}}: {{ $val | quote }}
    {{- end }}
spec:
  selector: 
    name: {{ .Values.generalInfo.name | default .Release.Name }}-pod
# What's the best practice of usage service type field? By default is the ClusterIP type
  # externalName: my.database.example.com
  type: {{ .Values.service.type }}
  ports:
  {{- if $ports }}
    {{- range $ports }}
      - name: {{ .name }}
        port: {{ .port }}
        targetPort: {{ .targetPort }}
        protocol: {{ .protocol }}
    {{- end}}
  {{- else }}
    - name: {{ $.Values.generalInfo.name | default $.Release.Name }}-svc
      port: {{ $.Values.service.externalPort | default "80" }}
      targetPort: {{ $.Values.deployment.containerPort | default "80" }}
      protocol: TCP
  {{- end }}

#   clusterIP:
# status:
#   loadBalancer:
#     ingress:
#     - ip: 192.0.2.127