{{ $ports := .Values.service.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.generalInfo.name | default .Release.Name }}-svc
  labels:
    {{- range $key, $value := .Values.generalInfo.labels -}}
      {{ $key | nindent 4}}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.annotations -}}
      {{ $key | nindent 4 }}: {{ $value | quote }}
    {{- end }}
spec:
  selector: 
    name: {{ .Values.generalInfo.name | default .Release.Name }}-pod
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
  {{- range $value := .Values.service.externalIPs}}
    - {{ $value | quote }}
  {{- end }}
  {{- end }}
  ports:
  {{- if $ports }}
      {{- tpl (toYaml $ports) $ | nindent 6 }}
  {{- else }}
    - name: {{ $.Values.generalInfo.name | default $.Release.Name }}-svc
      port: {{ $.Values.service.externalPort | default "80" }}
      targetPort: {{ $.Values.deployment.containerPort | default "80" }}
      protocol: TCP
  {{- end }}
clusterIP: {{ .Values.service.clusterIP }}
{{- if .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.ingress_ip }}
status:
  loadBalancer:
    ingress:
    - ip: {{ .Values.service.ingress_ip }}
  {{- end }}
{{- end -}}
